bgslogviewer:
  image: "bgslogviewer:0.1.4"
  ports:
    - "8080:8080"
  links:
    - redis
  volumes:
    - "./log:/app/log"
  environment:
    BLV_PROFILE: "false"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
redis:
  image: "redis:4.0.11"
  ports:
    - "6379:6379"
