bgslogviewer:
  image: "bgslogviewer:0.1.2"
  ports:
    - "8080:8080"
  restart: "unless-stopped"
  links:
    - redis
  environment:
    GIN_MODE: release
redis:
  image: "redis:4.0.11"
  ports:
    - "6379:6379"
