bgslogviewer:
  image: "bgslogviewer:0.1.7"
  ports:
    - "8080:8080"
  links:
    - redis
  volumes:
    - "./log:/app/log"
    - "./conf.d:/app/conf.d"
  environment:
    BLV_PROTO: "http"
    BLV_HOSTNAME: "localhost"
    BLV_PROFILE: "false"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    LOGLEVEL: "trace"
redis:
  image: "redis:4.0.11"
  ports:
    - "6379:6379"
