bgslogviewer:
  image: "bgslogviewer:0.1.4"
  ports:
    - "8080:8080"
  restart: "unless-stopped"
  links:
    - redis
  volumes:
    - "./log:/app/log"
  environment:
    GIN_MODE: release
redis:
  image: "redis:4.0.11"
  ports:
    - "6379:6379"
